rest_picker/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rest_picker.views.home', name='home'),
    # url(r'^rest_picker/', include('rest_picker.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rest_picker/',include('restaurants.urls', namespace="restaurants")),
)

restaurants/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView
from restaurants.models import Food
from django.conf import settings

urlpatterns = patterns('restaurants.views',
    url(r'^$',
        ListView.as_view(
            model=Food,
            template_name='restaurants/index.html'),
        name='index'),
    url(r'^food/(?P<food_id>\d+)/$', 'choose_town', name='choose_town'),
    url(r'^food/(?P<food_id>\d+)/town/(?P<town_id>\d+)/$', 'choose_restaurant', name='choose_restaurant'),
    url(r'^rest/(?P<rest_id>\d+)/$', 'restaurant', name='restaurant'),
    url(r'^(?P<rest_id>\d+)/vote/$', 'vote', name='vote'),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

restaurants/models.py
from django.db import models

class Food(models.Model):
    name = models.CharField(max_length=30)
    picture = models.ImageField(upload_to='images/', null=True)

    def __unicode__(self):
        return self.name

class Town(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=100)
    menu = models.CharField(max_length=100)
    web = models.CharField(max_length=100)
    phone = models.CharField(max_length=40)
    address = models.CharField(max_length=100)
    post_code = models.CharField(max_length=20)
    picture = models.ImageField(upload_to='images/', null=True)
    map = models.ImageField(upload_to='images/', null=True)
    gmap_url = models.CharField(max_length=200, null=True)

    food = models.ForeignKey(Food)
    town = models.ForeignKey(Town)

    STARS = (
        (1,'one'),
        (2,'two'),
        (3,'three'),
        (4,'four'),
    )
    votes = models.IntegerField(choices=STARS, default=4)

    def __unicode__(self):
        return self.name

restaurants/views.py
from django.shortcuts import render, get_object_or_404
from restaurants.models import Restaurant, Town 

# Create your views here.
def choose_town(request, food_id):

    rest_list = Restaurant.objects.filter(food=food_id)
    town_list=[]
    for r in rest_list:
        t = Town.objects.get(id=r.town.id)
        if t not in town_list:
            rests = Restaurant.objects.filter(food__id=food_id, town__id=t.id)
            town_list.append({'town':t, 'count':len(rests)})
    return render(request, 'restaurants/choose_town.html', {'food_id':food_id, 'town_list':town_list})

def choose_restaurant(request,food_id,town_id):
    rests = Restaurant.objects.filter(food__id=food_id, town__id=town_id)
    return render(request, 'restaurants/choose_restaurant.html', {'rests':rests})

def restaurant(request, rest_id, message=''):
    rest = Restaurant.objects.get(id=rest_id)
    rest_menu = rest.menu.split(';')
    rest_menu = [e for e in rest_menu if e not in ('',' ')]
    return render(request, 'restaurants/restaurant.html', {'restaurant':rest, 'rest_menu':rest_menu, 'message':message})

def vote(request, rest_id):
    rest = get_object_or_404(Restaurant, pk=rest_id)

    votes = rest.votes
    submitted = request.POST['note_utilisateur']
    average = (votes + int(submitted))/2
    rest.votes = average
    rest.save()

    rest_menu = rest.menu.split(';')
    rest_menu = [e for e in rest_menu if e not in ('',' ')]

    message='Thanks for your vote!'

    return render(request, 'restaurants/restaurant.html', {'restaurant':rest, 'rest_menu':rest_menu, 'message':message})

restaurants/templates/restaurants/choose_restaurant.html
{% load staticfiles %}
{% load url from future %}

<!DOCTYPE html> 
<html> 
<head> 
	<meta charset="UTF-8">
	<title>Restaurant Picker</title> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/jquery.mobile.structure-1.0.1.css' %}" />
    <link rel="apple-touch-icon" href="{% static 'restaurants/images/launch_icon_57.png' %}" />
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'restaurants/images/launch_icon_72.png' %}" />
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'restaurants/images/launch_icon_114.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/jquery.mobile-1.0.1.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/custom.css' %}" />
    <script type="text/javascript" src="{% static 'restaurants/js/jquery-1.7.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'restaurants/js/jquery.mobile-1.0.1.min.js' %}"></script>
</head> 

<body> 
<div id="choisir_restau" data-role="page" data-add-back-btn="true">
	<div data-role="header"> 
		<h1> Restaurant Picker</h1>
	</div> 
	<div data-role="content">
	    <div class="choice_list"> 
            <h1> Please choose a restaurant.</h1>
            {% if rests %}	
                <ul data-role="listview" data-inset="true" >
                    {% for r in rests %}
                    <li><a href="{% url 'restaurants:restaurant' r.id%}" data-transition="slidedown"> <img src={{ r.picture.url }}/> <h2>{{ r.name }}</h2> <p class="classement {{r.get_votes_display}}">{{r.votes}} stars  </p></a></li>
                    {% endfor %}
                </ul>	
            {% endif %}
    	</div>
	</div>
</div><!-- /page -->
</body>
</html>

restaurants/templates/restaurants/choose_town.html
{% load staticfiles %}
{% load url from future %}

<!DOCTYPE html> 
<html> 
<head> 
	 <meta charset="UTF-8">
	<title>Restaurant Picker</title> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/jquery.mobile.structure-1.0.1.css' %}" />
    <link rel="apple-touch-icon" href="{% static 'restaurants/images/launch_icon_57.png' %}" />
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'restaurants/images/launch_icon_72.png' %}" />
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'restaurants/images/launch_icon_114.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/jquery.mobile-1.0.1.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/custom.css' %}" />
    <script type="text/javascript" src="{% static 'restaurants/js/jquery-1.7.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'restaurants/js/jquery.mobile-1.0.1.min.js' %}"></script>
</head> 

<body> 
<div id="choisir_ville" data-role="page" data-add-back-btn="true">
	<div data-role="header"> 
		<h1> Restaurant Picker</h1>
	</div> 
	<div data-role="content">
	    <div class="choice_list"> 
        	<h1> In which town do you want to eat? </h1>
	        {% if town_list %}
            	<ul data-role="listview" data-inset="true" data-filter="true"  >
                    {% for town_dict in town_list %}
                            <li><a href="{% url 'restaurants:choose_restaurant' food_id town_dict.town.id %}"  data-transition="slidedown">{{ town_dict.town.name }}<span class="ui-li-count">{{ town_dict.count }}</span></a> </li>

                    {% endfor %}
	            </ul>
            {% endif %}
    	</div>
	</div>
</div><!-- /page -->
</body>
</html>

restaurants/templates/restaurants/index.html
{% load staticfiles %}
{% load url from future %}

<!DOCTYPE html> 
<html> 
	<head>
  <meta charset="UTF-8">	
	<title>Restaurant Picker</title> 
	
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/jquery.mobile.structure-1.0.1.css' %}" />
	<link rel="apple-touch-icon" href="{% static 'restaurants/images/launch_icon_57.png' %}" />
	<link rel="apple-touch-icon" sizes="72x72" href="{% static 'restaurants/images/launch_icon_72.png' %}" />
	<link rel="apple-touch-icon" sizes="114x114" href="{% static 'restaurants/images/launch_icon_114.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/jquery.mobile-1.0.1.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/custom.css' %}" />
    <script type="text/javascript" src="{% static 'restaurants/js/jquery-1.7.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'restaurants/js/jquery.mobile-1.0.1.min.js' %}"></script>

</head> 

<body> 
<div data-role="page" id="home" data-theme="c">
	<div data-role="content">
    	<div id="branding">
	    	<h1>Restaurant Picker </h1>
    	</div>
	
	    <div class="choice_list"> 
    	<h1> What would you'd like to eat? </h1>
        {% if food_list %}	
    	    <ul data-role="listview" data-inset="true" >
                {% for f in food_list %}
                <li><a href="{% url 'restaurants:choose_town' f.id %}" data-transition="slidedown"><img src={{f.picture.url}}/><h3>{{ f.name }}</h3></a></li>
                {% endfor %}
    	    </ul>	
	    {% endif%}
	</div>
	</div>

</div><!-- /page -->
</body>
</html>

restaurants/templates/restaurants/restaurant.html
{% load staticfiles %}
{% load url from future %}

<!DOCTYPE html> 
<html> 
<head> 
	<meta charset="UTF-8">
	<title>Restaurant Picker</title> 
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/jquery.mobile.structure-1.0.1.css' %}" />
    <link rel="apple-touch-icon" href="{% static 'restaurants/images/launch_icon_57.png' %}" />
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'restaurants/images/launch_icon_72.png' %}" />
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'restaurants/images/launch_icon_114.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/jquery.mobile-1.0.1.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'restaurants/custom.css' %}" />
    <script type="text/javascript" src="{% static 'restaurants/js/jquery-1.7.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'restaurants/js/jquery.mobile-1.0.1.min.js' %}"></script>
</head> 

<body> 
<div id="restau" data-role="page" data-add-back-btn="true">
	
	<div data-role="header"> 
		<h1> Restaurant Picker</h1>
	</div> 
	
	<div data-role="content">
        {% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
	<div class="ui-grid-a" id="restau_infos">	
		<div class="ui-block-a">
		    <h1>{{ restaurant.name }}</h1>
    		<p><strong>{{ restaurant.desc}}</strong></p>
	    	<p> On the menu: </p>
		    	<ul> 
                    {% for m in rest_menu %}
                        <li>{{m}}</li>
                    {% endfor %}
	    		</ul>			
		</div>		

		<div class="ui-block-b">
            <p><img src={{ restaurant.picture.url }} alt={{restaurant.name}} /></p>
	    	<p><a href="{{ restaurant.web }}" rel="external" data-role="button">See our website</a></p>
		</div>
	</div><!-- /grid-a -->

	<hr/>
	
	<div class="ui-grid-a" id="contact_infos">	
		<div class="ui-block-a">
    		<h2> Contact us</h2>
	    	<p>{{restaurant.address}}</p>
		    <p>{{restaurant.post_code}} {{restaurant.town }}</p>		
		</div>
		
		<div class="ui-block-b">
            <img src={{restaurant.map.url}} alt="map" />
		</div>
	</div><!-- /grid-a -->

	<div id="contact_buttons">	
        <a href="{{restaurant.gmap_url}}" data-role="button" data-icon="maps"> Find us on Google Maps </a> 	
		<a href="tel:{{restaurant.phone}}"  data-role="button" data-icon="tel"> Call us </a>	
	</div>	
	<hr/>
	
	<div id="notation">	
        <form action="{% url 'restaurants:vote' restaurant.id %}" method="post">
        {% csrf_token %}
	    <label for="select-choice-0" class="select"><h2> User rating </h2></label>
		<select name="note_utilisateur" onchange="this.form.submit()" id="note_utilisateur" data-native-menu="false" data-theme="c" >
           <option>Choose your vote</option>
		   <option value="1" class="one"> Not good at all </option>
		   <option value="2" class="two">Average </option>
		   <option value="3" class="three">Pretty good </option>
		   <option value="4" class="four"> Excellent </option>
		</select>	
	</form>
	</div>


	<script type="text/javascript">

	$( '#restau' ).live( 'pageinit',function(event){
		var SelectedOptionClass = $('option:selected').attr('class');
		$('div.ui-select').addClass(SelectedOptionClass);
		
		$('#note_utilisateur').live('change', function(){	 
			$('div.ui-select').removeClass(SelectedOptionClass);
			
			SelectedOptionClass = $('option:selected').attr('class');
			$('div.ui-select').addClass(SelectedOptionClass);		
			
		 });
		
	  
	});

	</script>
	

	</div>


</div><!-- /page -->
</body>
</html>